### ISSUE TITLE
Type me.gilo.woodroid.models.Download is defined multple times

### ISSUE THREAD

**Issue by omarsalazars** [gilokimu/woocommerce-android-sdk#12]
I cloned the project and when I try to build it I get the following error:

:app:multiDexListDebug
Type me.gilo.woodroid.models.Download is defined multiple times: /home/omar/Documents/WooDroid/woodroid/build/intermediates/runtime_library_classes/debug/classes.jar:me/gilo/woodroid/models/Download.class, /home/omar/Documents/WooDroid/firebasecart/build/intermediates/runtime_library_classes/classes.jar:me/gilo/woodroid/models/Download.class

I think this is due to both classes with the same name, I will refactor firebasecart Download class and see what happens. 

You're doing a great job with this project, thanks

**Comment by ItsAnubhav** [comment]
I am also getting the same issue

**Comment by omarsalazars** [comment]
As a temporary solution, I erased my android studio IDE and installed it using Jetbrains Toolbox. I don't know why but it worked.

**Comment by gilokimu** [comment]
I will take a look at the issue this week.

**Comment by Sciffleaf** [comment]
hello, thanks for the project sir, you're doing great, however, im still getting the same error with this issue, is there any solution?
