### ISSUE TITLE
"Invalid signature - provided signature does not match."

### ISSUE THREAD

**Issue by User17745** [gilokimu/woocommerce-android-sdk#13]
First off, my apologies, I didn't want to open an issue for a support query but I couldn't find any alternative way to reach out (slack maybe?).

I'm a novice Android and WooCommerce developer and I'm trying to access a store using WooDroid but I'm getting the following response whenever I try to grab response from the `onResponse`  method:

`
{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}
`

I setup the new WP REST API integration using the store's credentials (URL, CK and CS) and double checked them. Everything is working fine in Postman.

**Comment by gilokimu** [comment]
Hello, I added a slack channel to provide this type of support. You can reach me through: https://woodroid.slack.com/
