### ISSUE TITLE
How to check coupon code valid or not?

### ISSUE THREAD

**Issue by Lalitchaudhary2** [gilokimu/woocommerce-android-sdk#15]
I developed one e-commerce app using woocommerce rest-API. now I need to add coupons codes feature in-app. I know how to pass coupon code in creating order, but how to check this code is valid or not before creating an order?

**Comment by gilokimu** [comment]
You can use this endpoint: https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-coupon.
Basically, make this call `woocommerce.CouponRepository().coupon(couponId) ` before creating an order
