### ISSUE TITLE
After Product is updated, all associated attributes are removed

### ISSUE THREAD

**Issue by hoba-dafidi** [gilokimu/woocommerce-android-sdk#16]
Great work!
But I have issues with product update. After the Update API returns successful, the product will have an empty attributes array.

For example, if I updated a product which have 2 attributes Colour and Size. By the time I called load product from the database, all the attributes are gone.

Please can you help?
Thank you

**Comment by gilokimu** [comment]
Please provide the request details you made and response gotten / expected response

**Comment by hoba-dafidi** [comment]
Thank you for your prompt response.
This is the product i want to update
![att1](https://user-images.githubusercontent.com/49867384/75671686-7adb0f00-5c7f-11ea-92f7-ece68b440163.JPG)
![att2](https://user-images.githubusercontent.com/49867384/75671707-83cbe080-5c7f-11ea-9fa2-986af7aa6e85.JPG)
![att3](https://user-images.githubusercontent.com/49867384/75671716-8a5a5800-5c7f-11ea-8d7c-0ab5a4be2a2e.JPG)


I followed your examples

In **ViewModel**:
public WooLiveData<Product> updateProduct(int id, Product product) {
        return productRepository.update(id, product);
    }

and the **ProductRepository**
public WooLiveData<Product> update(int id, Product product) {
        final WooLiveData<Product> callBack = new WooLiveData();

        woocommerce.ProductRepository().update(id, product).enqueue(callBack);
        return callBack;
    }

This is the response:
![res1](https://user-images.githubusercontent.com/49867384/75671791-aeb63480-5c7f-11ea-914d-81625b20df92.JPG)
![res2](https://user-images.githubusercontent.com/49867384/75671800-b37ae880-5c7f-11ea-8382-0062672a2d33.JPG)
![res3](https://user-images.githubusercontent.com/49867384/75671815-b83f9c80-5c7f-11ea-9913-1a4e3cf61d56.JPG)


As you can see, the attributes are gone. When I check it on the woocommerce site, there is no attribute associated with it again but the Attributes are still listed in the Attribute page on the admin site

**Comment by gilokimu** [comment]
I am not able to fix this at the moment, but I do believe the issue is because of the field productAttributes in the Product class, needs to have an attribute
```
@SerializedName("attributes")
lateinit var productAttributes: ArrayList<ProductAttribute>
```

**Comment by hoba-dafidi** [comment]
I finally found the solution.
The attributes in the Product object to be updated has its visible and variable properties set to false and the option property set to null.

So, I have to correct those and it worked.
Thank you for your time sir
