### ISSUE TITLE
Sign in through customer credentials

### ISSUE THREAD

**Issue by themalikx** [gilokimu/woocommerce-android-sdk#18]
Is it possible to sign in through customer credentials, or restrict the android client to access data for only currently signed in customer user, not all of the data that is related to admins?

**Comment by gilokimu** [comment]
There is no API endpoint to log in or register into the store. At least not that I know of.

**Comment by themalikx** [comment]
Yes, I know but it should be created to completely support mobile devices to consume WooCommerce API to build store app.

**Comment by gilokimu** [comment]
I don't have control over that though, but I agree with you 100%. There are a few crucial endpoints we are missing from Woocommerce. You will have to use your own auth or maybe there might be a plugin to support this.

**Comment by themalikx** [comment]
Yes, thanks. Now I'm writing own plugin.

**Comment by gilokimu** [comment]
Ok, do let me know once the plugin Is done, I might consider integrating into it

**Comment by rital-naik-adrosonic** [comment]
Hi @gilokimu , has authentication been integrated to this library now?
