### ISSUE TITLE
Cart Woo endpoint

### ISSUE THREAD

**Issue by ProgrammerN** [gilokimu/woocommerce-android-sdk#4]
404 Not Found https://example.com/wp-json/wc/v2/cart
The woocommerce rest API seems not to have such an endpoint.Instead you should use oders endpoint and handle the cart in your own way

**Comment by gilokimu** [comment]
You have to use this https://github.com/co-cart/co-cart plugin, however I was not able to get it to work, I will pull down the cart endpoint until when I find a better solution

**Comment by ProgrammerN** [comment]
I seem to have noticed that issue with cookies but however they still fail at some point.Adding both interceptors at once has issues and you have to make a separate connection for received cookies and  another for add cookies data respectively with receiving cart information and sending cart data.

**Comment by gilokimu** [comment]
That is literally what I had done, see below
```java
OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(new AddCookiesInterceptor(context))
                .addInterceptor(new ReceivedCookiesInterceptor(context))
                .addInterceptor(loggingInterceptor)
                .readTimeout(30, TimeUnit.SECONDS)
                .writeTimeout(30, TimeUnit.SECONDS)
                .connectTimeout(15, TimeUnit.SECONDS)
                .build();
```
I would intercept on any request to cart and add the cookies and capture any response from the cart api and store cookies. The implemented cart api does not work with woocommerce authentication

**Comment by gilokimu** [comment]
This has now been implemented through firebase but on the sample app
